### PR TITLE
Bugfix/backend 841

### PR DESCRIPTION
**Pull request by hochung**
- Fail creation of entity data if user doesn't have write access to all key property types
- `BootstrapDatastoreWithCassandra` can't start up sometimes because of a `SocketTimeOutError` when logging into the four different test accounts. Auth0 Free Tier is imposing a rate limit of [2 API calls per second](https://auth0.com/docs/connections/database/rate-limits), causing the issue. Fixing this by sleeping 2 seconds after each login of test account.

### CODE REVIEW

**Comment by hochung** [comment]
looks like there is still a thread interference in bamboo even after I added Thread.sleep :/

**Review by geekbeast — CHANGES_REQUESTED** [review]
This should work better than sleeping threads :) 
https://github.com/kryptnostic/rhizome/pull/188

**Comment by hochung** [comment]
👍 that's cool!

**Review by geekbeast — APPROVED** [review]

**Comment by geekbeast** [comment]
@hochung What is missing to merge this?

**Comment by hochung** [comment]
Changes in BACKEND-859, one sec

**Comment by hochung** [comment]
Looks like it's Katherine's branch for TopUtilizers

**Pull request merged**
