### PR TITLE
filter out null bytes from codex messages

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Review by makosblade — APPROVED** [review]
:'(

**Review by geekbeast — APPROVED** [review]
My one concern here is that we don't understand why this is happening. Have we reached out to Twilio?

**Comment by makosblade** [comment]
> My one concern here is that we don't understand why this is happening. Have we reached out to Twilio?

It sounded like the issue is that Twilio just passes on the source encoding, in this case GSM-7 which allows null bytes that get v.sad when you attempt to interpret them as UTF-8

**Comment by geekbeast** [comment]
Hmm, why not? http://opensmpp.org/

**Pull request merged**
